### ISSUE TITLE
Importance of granular_third_quartile_coverage, granular_median_coverage, granular_first_quartile_coverage, perc_bases_above_15 in sampleInfo.example file.

### ISSUE THREAD

**Issue by Manikumarksr** [mills-lab/dinumt#4]
We are facing problems while running GATK to calculate granular_third_quartile_coverage, granular_median_coverage, granular_first_quartile_coverage, perc_bases_above_15 mentioned in sampleInfo.example file. Are those parameters are necessary for the "gnomit" script or just the extra information? Can you please clarify this ASAP. Thank you

**Comment by remills** [comment]
Hi! Yeah, dinumt/gnomit was written a while ago and GATK has changed a lot since then; those fields were basically just pulled from the DepthOfCoverage module and included in case we ever needed them, but the program doesn't require them and you can likely just put 'NA' or '0' in the fields for the file or remove those columns entirely since it's based on the header label.

**Comment by Manikumarksr** [comment]
Thank you soo much for the clarification.
